#!/bin/bash
mkdir -p /resultVolume/D27_Samsung_GalaxyS5/videosflatYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D27_V_flatYT_move_0001.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosflatYT/D27_V_flatYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D27_V_flatYT_move_0002.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosflatYT/D27_V_flatYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D27_V_flatYT_move_0003.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosflatYT/D27_V_flatYT_move_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D27_V_flatYT_panrot_0001.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosflatYT/D27_V_flatYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D27_V_flatYT_panrot_0002.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosflatYT/D27_V_flatYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D27_V_flatYT_still_0001.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosflatYT/D27_V_flatYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D27_V_flatYT_still_0002.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosflatYT/D27_V_flatYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D27_Samsung_GalaxyS5/videosindoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D27_V_indoorYT_move_0001.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosindoorYT/D27_V_indoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D27_V_indoorYT_move_0002.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosindoorYT/D27_V_indoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D27_V_indoorYT_panrot_0001.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosindoorYT/D27_V_indoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D27_V_indoorYT_panrot_0002.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosindoorYT/D27_V_indoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D27_V_indoorYT_still_0001.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosindoorYT/D27_V_indoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D27_V_indoorYT_still_0002.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosindoorYT/D27_V_indoorYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D27_Samsung_GalaxyS5/videosoutdoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D27_V_outdoorYT_move_0001.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosoutdoorYT/D27_V_outdoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D27_V_outdoorYT_move_0002.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosoutdoorYT/D27_V_outdoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D27_V_outdoorYT_panrot_0001.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosoutdoorYT/D27_V_outdoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D27_V_outdoorYT_panrot_0002.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosoutdoorYT/D27_V_outdoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D27_V_outdoorYT_still_0001.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosoutdoorYT/D27_V_outdoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D27_V_outdoorYT_still_0002.mp4 /resultVolume/D27_Samsung_GalaxyS5/videosoutdoorYT/D27_V_outdoorYT_still_0002.mat 3 8 1 /tempVolume
