#!/bin/bash
mkdir -p /resultVolume/D16_Huawei_P9Lite/videosflatYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D16_V_flatYT_move_0001.mp4 /resultVolume/D16_Huawei_P9Lite/videosflatYT/D16_V_flatYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D16_V_flatYT_move_0002.mp4 /resultVolume/D16_Huawei_P9Lite/videosflatYT/D16_V_flatYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D16_V_flatYT_move_0003.mp4 /resultVolume/D16_Huawei_P9Lite/videosflatYT/D16_V_flatYT_move_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D16_V_flatYT_panrot_0001.mp4 /resultVolume/D16_Huawei_P9Lite/videosflatYT/D16_V_flatYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D16_V_flatYT_panrot_0002.mp4 /resultVolume/D16_Huawei_P9Lite/videosflatYT/D16_V_flatYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D16_V_flatYT_still_0001.mp4 /resultVolume/D16_Huawei_P9Lite/videosflatYT/D16_V_flatYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D16_V_flatYT_still_0002.mp4 /resultVolume/D16_Huawei_P9Lite/videosflatYT/D16_V_flatYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D16_Huawei_P9Lite/videosindoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D16_V_indoorYT_move_0001.mp4 /resultVolume/D16_Huawei_P9Lite/videosindoorYT/D16_V_indoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D16_V_indoorYT_move_0002.mp4 /resultVolume/D16_Huawei_P9Lite/videosindoorYT/D16_V_indoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D16_V_indoorYT_panrot_0001.mp4 /resultVolume/D16_Huawei_P9Lite/videosindoorYT/D16_V_indoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D16_V_indoorYT_panrot_0002.mp4 /resultVolume/D16_Huawei_P9Lite/videosindoorYT/D16_V_indoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D16_V_indoorYT_still_0001.mp4 /resultVolume/D16_Huawei_P9Lite/videosindoorYT/D16_V_indoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D16_V_indoorYT_still_0002.mp4 /resultVolume/D16_Huawei_P9Lite/videosindoorYT/D16_V_indoorYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D16_Huawei_P9Lite/videosoutdoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D16_V_outdoorYT_move_0001.mp4 /resultVolume/D16_Huawei_P9Lite/videosoutdoorYT/D16_V_outdoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D16_V_outdoorYT_move_0002.mp4 /resultVolume/D16_Huawei_P9Lite/videosoutdoorYT/D16_V_outdoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D16_V_outdoorYT_panrot_0001.mp4 /resultVolume/D16_Huawei_P9Lite/videosoutdoorYT/D16_V_outdoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D16_V_outdoorYT_panrot_0002.mp4 /resultVolume/D16_Huawei_P9Lite/videosoutdoorYT/D16_V_outdoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D16_V_outdoorYT_still_0001.mp4 /resultVolume/D16_Huawei_P9Lite/videosoutdoorYT/D16_V_outdoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D16_V_outdoorYT_still_0002.mp4 /resultVolume/D16_Huawei_P9Lite/videosoutdoorYT/D16_V_outdoorYT_still_0002.mat 3 8 1 /tempVolume
