#!/bin/bash
mkdir -p /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_move_0001.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_move_0002.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_move_0003.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_move_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_move_0004.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_move_0004.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_panrot_0001.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_panrot_0002.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_panrot_0003.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_panrot_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_panrot_0004.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_panrot_0004.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_still_0001.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_still_0002.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_still_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_still_0003.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_still_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_still_0004.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_still_0004.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D08_V_flatYT_still_0005.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosflatYT/D08_V_flatYT_still_0005.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D08_V_indoorYT_move_0001.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT/D08_V_indoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D08_V_indoorYT_move_0002.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT/D08_V_indoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D08_V_indoorYT_move_0003.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT/D08_V_indoorYT_move_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D08_V_indoorYT_move_0004.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT/D08_V_indoorYT_move_0004.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D08_V_indoorYT_panrot_0001.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT/D08_V_indoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D08_V_indoorYT_panrot_0002.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT/D08_V_indoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D08_V_indoorYT_still_0001.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT/D08_V_indoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D08_V_indoorYT_still_0002.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT/D08_V_indoorYT_still_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D08_V_indoorYT_still_0003.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosindoorYT/D08_V_indoorYT_still_0003.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_move_0001.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_move_0002.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_move_0003.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_move_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_move_0004.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_move_0004.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_panrot_0001.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_panrot_0002.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_panrot_0003.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_panrot_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_panrot_0004.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_panrot_0004.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_still_0001.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_still_0002.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_still_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_still_0003.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_still_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D08_V_outdoorYT_still_0004.mp4 /resultVolume/D08_Samsung_GalaxyTab3/videosoutdoorYT/D08_V_outdoorYT_still_0004.mat 3 8 1 /tempVolume
