#!/bin/bash
mkdir -p /resultVolume/D30_Huawei_Honor5c/videosflatYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D30_V_flatYT_move_0001.mp4 /resultVolume/D30_Huawei_Honor5c/videosflatYT/D30_V_flatYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D30_V_flatYT_move_0002.mp4 /resultVolume/D30_Huawei_Honor5c/videosflatYT/D30_V_flatYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D30_V_flatYT_move_0003.mp4 /resultVolume/D30_Huawei_Honor5c/videosflatYT/D30_V_flatYT_move_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D30_V_flatYT_panrot_0001.mp4 /resultVolume/D30_Huawei_Honor5c/videosflatYT/D30_V_flatYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D30_V_flatYT_panrot_0002.mp4 /resultVolume/D30_Huawei_Honor5c/videosflatYT/D30_V_flatYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D30_V_flatYT_still_0001.mp4 /resultVolume/D30_Huawei_Honor5c/videosflatYT/D30_V_flatYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D30_V_flatYT_still_0002.mp4 /resultVolume/D30_Huawei_Honor5c/videosflatYT/D30_V_flatYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D30_Huawei_Honor5c/videosindoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D30_V_indoorYT_move_0001.mp4 /resultVolume/D30_Huawei_Honor5c/videosindoorYT/D30_V_indoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D30_V_indoorYT_move_0002.mp4 /resultVolume/D30_Huawei_Honor5c/videosindoorYT/D30_V_indoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D30_V_indoorYT_panrot_0001.mp4 /resultVolume/D30_Huawei_Honor5c/videosindoorYT/D30_V_indoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D30_V_indoorYT_panrot_0002.mp4 /resultVolume/D30_Huawei_Honor5c/videosindoorYT/D30_V_indoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D30_V_indoorYT_still_0001.mp4 /resultVolume/D30_Huawei_Honor5c/videosindoorYT/D30_V_indoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D30_V_indoorYT_still_0002.mp4 /resultVolume/D30_Huawei_Honor5c/videosindoorYT/D30_V_indoorYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D30_Huawei_Honor5c/videosoutdoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D30_V_outdoorYT_move_0001.mp4 /resultVolume/D30_Huawei_Honor5c/videosoutdoorYT/D30_V_outdoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D30_V_outdoorYT_move_0002.mp4 /resultVolume/D30_Huawei_Honor5c/videosoutdoorYT/D30_V_outdoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D30_V_outdoorYT_panrot_0001.mp4 /resultVolume/D30_Huawei_Honor5c/videosoutdoorYT/D30_V_outdoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D30_V_outdoorYT_panrot_0002.mp4 /resultVolume/D30_Huawei_Honor5c/videosoutdoorYT/D30_V_outdoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D30_V_outdoorYT_still_0001.mp4 /resultVolume/D30_Huawei_Honor5c/videosoutdoorYT/D30_V_outdoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D30_V_outdoorYT_still_0002.mp4 /resultVolume/D30_Huawei_Honor5c/videosoutdoorYT/D30_V_outdoorYT_still_0002.mat 3 8 1 /tempVolume
