#!/bin/bash
mkdir -p /resultVolume/D26_Samsung_GalaxyS3Mini/videosflatYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D26_V_flatYT_move_0001.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosflatYT/D26_V_flatYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D26_V_flatYT_move_0002.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosflatYT/D26_V_flatYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D26_V_flatYT_panrot_0001.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosflatYT/D26_V_flatYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D26_V_flatYT_still_0001.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosflatYT/D26_V_flatYT_still_0001.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D26_Samsung_GalaxyS3Mini/videosindoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D26_V_indoorYT_move_0001.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosindoorYT/D26_V_indoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D26_V_indoorYT_move_0002.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosindoorYT/D26_V_indoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D26_V_indoorYT_panrot_0001.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosindoorYT/D26_V_indoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D26_V_indoorYT_panrot_0002.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosindoorYT/D26_V_indoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D26_V_indoorYT_still_0001.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosindoorYT/D26_V_indoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D26_V_indoorYT_still_0002.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosindoorYT/D26_V_indoorYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D26_Samsung_GalaxyS3Mini/videosoutdoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D26_V_outdoorYT_move_0001.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosoutdoorYT/D26_V_outdoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D26_V_outdoorYT_move_0002.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosoutdoorYT/D26_V_outdoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D26_V_outdoorYT_panrot_0001.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosoutdoorYT/D26_V_outdoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D26_V_outdoorYT_panrot_0002.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosoutdoorYT/D26_V_outdoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D26_V_outdoorYT_still_0001.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosoutdoorYT/D26_V_outdoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D26_V_outdoorYT_still_0002.mp4 /resultVolume/D26_Samsung_GalaxyS3Mini/videosoutdoorYT/D26_V_outdoorYT_still_0002.mat 3 8 1 /tempVolume
