#!/bin/bash
mkdir -p /resultVolume/D35_Samsung_GalaxyTabA/videosflatYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D35_V_flatYT_move_0001.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosflatYT/D35_V_flatYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D35_V_flatYT_move_0002.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosflatYT/D35_V_flatYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D35_V_flatYT_panrot_0001.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosflatYT/D35_V_flatYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D35_V_flatYT_still_0001.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosflatYT/D35_V_flatYT_still_0001.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D35_Samsung_GalaxyTabA/videosindoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D35_V_indoorYT_move_0001.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosindoorYT/D35_V_indoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D35_V_indoorYT_move_0002.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosindoorYT/D35_V_indoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D35_V_indoorYT_panrot_0001.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosindoorYT/D35_V_indoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D35_V_indoorYT_panrot_0002.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosindoorYT/D35_V_indoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D35_V_indoorYT_still_0001.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosindoorYT/D35_V_indoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D35_V_indoorYT_still_0002.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosindoorYT/D35_V_indoorYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D35_Samsung_GalaxyTabA/videosoutdoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D35_V_outdoorYT_move_0001.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosoutdoorYT/D35_V_outdoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D35_V_outdoorYT_move_0002.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosoutdoorYT/D35_V_outdoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D35_V_outdoorYT_panrot_0001.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosoutdoorYT/D35_V_outdoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D35_V_outdoorYT_panrot_0002.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosoutdoorYT/D35_V_outdoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D35_V_outdoorYT_still_0001.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosoutdoorYT/D35_V_outdoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D35_V_outdoorYT_still_0002.mp4 /resultVolume/D35_Samsung_GalaxyTabA/videosoutdoorYT/D35_V_outdoorYT_still_0002.mat 3 8 1 /tempVolume
