#!/bin/bash
mkdir -p /resultVolume/D09_Apple_iPhone4/videosflatYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D09_V_flatYT_move_0001.mp4 /resultVolume/D09_Apple_iPhone4/videosflatYT/D09_V_flatYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D09_V_flatYT_move_0002.mp4 /resultVolume/D09_Apple_iPhone4/videosflatYT/D09_V_flatYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D09_V_flatYT_move_0003.mp4 /resultVolume/D09_Apple_iPhone4/videosflatYT/D09_V_flatYT_move_0003.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D09_V_flatYT_panrot_0001.mp4 /resultVolume/D09_Apple_iPhone4/videosflatYT/D09_V_flatYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D09_V_flatYT_panrot_0002.mp4 /resultVolume/D09_Apple_iPhone4/videosflatYT/D09_V_flatYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D09_V_flatYT_still_0001.mp4 /resultVolume/D09_Apple_iPhone4/videosflatYT/D09_V_flatYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/flatYT/D09_V_flatYT_still_0002.mp4 /resultVolume/D09_Apple_iPhone4/videosflatYT/D09_V_flatYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D09_Apple_iPhone4/videosindoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D09_V_indoorYT_move_0001.mp4 /resultVolume/D09_Apple_iPhone4/videosindoorYT/D09_V_indoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D09_V_indoorYT_move_0002.mp4 /resultVolume/D09_Apple_iPhone4/videosindoorYT/D09_V_indoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D09_V_indoorYT_panrot_0001.mp4 /resultVolume/D09_Apple_iPhone4/videosindoorYT/D09_V_indoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D09_V_indoorYT_panrot_0002.mp4 /resultVolume/D09_Apple_iPhone4/videosindoorYT/D09_V_indoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D09_V_indoorYT_still_0001.mp4 /resultVolume/D09_Apple_iPhone4/videosindoorYT/D09_V_indoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/indoorYT/D09_V_indoorYT_still_0002.mp4 /resultVolume/D09_Apple_iPhone4/videosindoorYT/D09_V_indoorYT_still_0002.mat 3 8 1 /tempVolume
mkdir -p /resultVolume/D09_Apple_iPhone4/videosoutdoorYT
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D09_V_outdoorYT_move_0001.mp4 /resultVolume/D09_Apple_iPhone4/videosoutdoorYT/D09_V_outdoorYT_move_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D09_V_outdoorYT_move_0002.mp4 /resultVolume/D09_Apple_iPhone4/videosoutdoorYT/D09_V_outdoorYT_move_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D09_V_outdoorYT_panrot_0001.mp4 /resultVolume/D09_Apple_iPhone4/videosoutdoorYT/D09_V_outdoorYT_panrot_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D09_V_outdoorYT_panrot_0002.mp4 /resultVolume/D09_Apple_iPhone4/videosoutdoorYT/D09_V_outdoorYT_panrot_0002.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D09_V_outdoorYT_still_0001.mp4 /resultVolume/D09_Apple_iPhone4/videosoutdoorYT/D09_V_outdoorYT_still_0001.mat 3 8 1 /tempVolume
sh  /run_buildSaveVideoFrameMasks_withThreshold_and_Fingerprint.sh /opt/mcr/v95 /videosDistantVolume/outdoorYT/D09_V_outdoorYT_still_0002.mp4 /resultVolume/D09_Apple_iPhone4/videosoutdoorYT/D09_V_outdoorYT_still_0002.mat 3 8 1 /tempVolume
